### ISSUE TITLE
Shared Memory too low

### ISSUE THREAD

**Issue by 0x46616c6b** [devture/com.devture.ansible.role.postgres#2]
Hello,

I have stumbled across the problem

> ERROR:  could not resize shared memory segment "/PostgreSQL.3430778118" to 333465184 bytes: No space left on device

It seems that [256m](https://github.com/devture/com.devture.ansible.role.postgres/blob/main/templates/systemd/postgres.service.j2#L29) is not enough. Shouldn't a variable be introduced here or maybe the option to mount the shared memory from the host system?

**Comment by spantaleev** [comment]
What were you doing when you got this error? Was it during normal Postgres usage, or were you trying to do a vacuum or database import?

It doesn't hurt to raise it, and to also make it configurable.

**Comment by 0x46616c6b** [comment]
I use it in the a Matrix Setup and we activate `autovacuum` for Postgres. But the `ANALYZE` (and always `VACUUM`) w/o force will not work for our table sizes. So I would like to increase it and use the non-blocking vacuuming to have no downtime. 

If you agree, I can prepare a PR for that.

**Comment by spantaleev** [comment]
Sure! Please prepare a PR!
