### ISSUE TITLE
;ansible-playbook -i inventory/hosts setup.yml --tags=setup-all fails

### ISSUE THREAD

**Issue by alongls** [devture/com.devture.ansible.role.postgres#5]
when running the setup-all command now with the new devture postgres parameters the Ansible fails
in the vars.yml file i updated 2 lines:
## Postgres Database Data ##
devture_postgres_enabled: true
devture_postgres_connection_password: '1234qwer'

i also ran the command make roles to download new roles
than when running the playbook using the command:
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,start --ask-become-pass

it fails with the error:

fatal: [connectsvr.hots.com]: FAILED! => changed=true
  cmd:
  - /usr/bin/env
  - docker
  - run
  - --rm
  - --user=998:1000
  - --cap-drop=ALL
  - --env-file=/connect/postgres/env-postgres-psql
  - --network=matrix
  - --mount
  - type=bind,src=/tmp/matrix-postgres-init-managed-db-user-and-role.sql,dst=/matrix-postgres-init-managed-db-user-and-role.sql,ro
  - --entrypoint=/bin/sh
  - docker.io/postgres:15.1-alpine
  - -c
  - psql -h matrix-postgres --file=/matrix-postgres-init-managed-db-user-and-role.sql
  delta: '0:00:01.713615'
  end: '2022-12-07 12:59:57.737566'
  msg: non-zero return code
  rc: 2
  start: '2022-12-07 12:59:56.023951'
  ****stderr: 'psql: error: could not translate host name "matrix-postgres" to address: Name does not resolve'****
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

any idea what is wrong now after changing the parameters ?

thanks

**Comment by alongls** [comment]
i dont know how but the issue is resolved

**Comment by spantaleev** [comment]
Your server was probably somewhat overloaded and Postgres was slow to start, I suppose.
